server:
  port: 19012
eureka:
  client:
    service-url:
      defaultZone: ${eureka.url}
zuul:
  ignored-services: '*'
  routes:
    com-platform-front-web: /web/**
logging:
  level:
    com.netflix: debug
  file:
    name: ../log/platform-zuul.log
spring:
  application:
    name: com-platform-zuul